### ISSUE TITLE
Unable to get auto-completion with #[derive(Builder)]

### ISSUE THREAD

**Issue by PreetamSing** [BrynCooke/buildstructor#106] opened 2023-02-15 09:54 UTC
I'm using `buildstructor` as following.
```rust
#[derive(buildstructor::Builder)]
pub struct JWTHelper {
    pvt_key_secret: Option<String>,
    // ...
}

fn main() {
    let jwt_helper = JWTHelper::builder().pvt_key_secret("abcd".to_string()).build();
}
```

Also, I'm using rust-analyzer, editor: Neovim.
Issue: I'm unable to get autocompletion for any method related to `Builder` from rust-analyzer, starting from `builder` method to `build` method. Other custom implemented methods are showing up.
Though, of course, it's compiling fine.

**Comment by BrynCooke** [comment] 2023-03-19 15:27
I'm not sure what the issue is. I seem to get code completion OK both with vscode (rust-analyzer) and intelliJ Rust.

**Comment by BrynCooke** [comment] 2023-04-08 15:28
Gonna close this as can't reproduce.

**Closed as completed by BrynCooke** 2023-04-08 15:28 UTC
